- LICENSE
> add-license-1

- tamcolors/checks/__init__.py
- tamcolors/tma/tma_buffer.py
> fix checks

- tamcolors/tests/tma/tests.py
- tamcolors/tma/win_tma.py
> remove switch

- tamcolors/tests/tma/tests.py
- tamcolors/tma/uni_tma.py
> clean up mac

- .gitignore
> remove egg dir

- tamcolors/tam/_uni_tma/_uni_tma.cpp
- tamcolors/tam/_uni_tma/uni_tma.cpp
- tamcolors/tam/_uni_tma/uni_tma.h
- tamcolors/tam/_win_tma/_win_tma.cpp
- tamcolors/tam/_win_tma/win_tma.cpp
- tamcolors/tam/_win_tma/win_tma.h
- tamcolors/tam/any_tma.py
- tamcolors/tam/io_tma.py
- tamcolors/tam/tma_buffer.py
- tamcolors/tam/tma_colors.py
- tamcolors/tam/tma_keys.py
- tamcolors/tam/tma_loop.py
- tamcolors/tam/tma_loop_test.py
- tamcolors/tam/uni_tma.py
- tamcolors/tam/win_tma.py
- tamcolors/tam_tools/tma_color_palette.py
- tamcolors/tam_tools/tma_fade.py
- tamcolors/tam_tools/tma_film.py
- tamcolors/tam_tools/tma_key_manager.py
- tamcolors/tam_tools/tma_list_buffer.py
- tamcolors/tam_tools/tma_menu.py
- tamcolors/tam_tools/tma_placing.py
- tamcolors/tests/tam/tests.py
- tamcolors/tests/tam_tools/tests.py
> remove_charels

- tamcolors/__init__.py
- tamcolors/examples/__init__.py
- tamcolors/examples/basic.py
- tamcolors/tam_basic/__init__.py
- tamcolors/tam_basic/basic.py
- tamcolors/tam_c/_win_tam/_win_tam.cpp
- tamcolors/tam_c/_win_tam/win_tam.cpp
- tamcolors/tam_c/_win_tam/win_tam.h
- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
> add printc to win

- tamcolors/tam_io/uni_tam.py
- tamcolors/tests/tam_io/uni_tam_tests.py
> make printc work on uni

- setup.py
- tamcolors/examples/icon.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_test.py
- tamcolors/tests/tam/tam_loop_test_tests.py
- tamcolors/tests/tam/tam_loop_tests.py
> change tamframe

- README.md
- tamcolors/examples/basic.py
- tamcolors/examples/icon.py
- tamcolors/tam_tools/__init__.py
- tamcolors/tam_tools/tam_icon.py
> update examples and readme

- setup.py
- tamcolors/README.md
- tamcolors/__init__.py
> add read me

- README.rst
- tamcolors/README.rst
> move_all_md_over

- setup.py
> add setuptools

- setup.py
> remove_3_4_support

- README.rst
- tamcolors/README.rst
> 1_0_3_goals

- tamcolors/README.rst
> test badge

- README.rst
- tamcolors/README.rst
- tamcolors/examples/basic.py
- tamcolors/tam_basic/basic.py
- tamcolors/tam_io/tam_colors.py
- tamcolors/tam_io/win_tam.py
> add default color for windows

- tamcolors/tam_io/uni_tam.py
- tamcolors/tests/tam_io/uni_tam_tests.py
> add uni default colors

- setup.py
- tamcolors/docs/source/conf.py
> add rtd theme

- .gitignore
> add build ignore

- tamcolors/tam_io/win_tam.py
- tamcolors/tests/__init__.py
- tamcolors/tests/tam_basic/__init__.py
- tamcolors/tests/tam_basic/basic_tests.py
- tamcolors/tests/tam_io/uni_tam_tests.py
- tamcolors/tests/tam_io/win_tam_tests.py
> add tam basic tests and some io tests

- tamcolors/tests/tam_io/uni_tam_tests.py
> fix uni io test

- tamcolors/examples/__init__.py
- tamcolors/examples/tam_loop.py
- tamcolors/examples/tam_print.py
- tamcolors/examples/tam_text_box.py
> add more examples

- README.rst
> add linke to readme

- tamcolors/examples/__init__.py
- tamcolors/examples/tam_list_buffer.py
> add more exampels

- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_test.py
- tamcolors/tests/tam/tam_loop_tests.py
> clean up tam loop

- README.rst
> tag and update readme

- setup.py
> add basic tests

- tamcolors/tam_basic/basic.py
- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
- tamcolors/tests/tam_basic/basic_tests.py
> add flush to basic

- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
> clean_up_win_tam

- tamcolors/examples/__init__.py
- tamcolors/examples/alpha.py
- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/tam_buffer.py
- tamcolors/tam_io/tam_colors.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
- tamcolors/tests/tam_io/tam_buffer_tests.py
- tamcolors/tests/tam_io/uni_tam_tests.py
- tamcolors/tests/tam_io/win_tam_tests.py
- tamcolors/tests/tam_tools/tam_print_tests.py
> add alpha with example and tests

- tamcolors/tests/tam_io/tam_buffer_tests.py
> add replace alpha chars

- tamcolors/tam_io/uni_tam.py
- tamcolors/tests/tam_io/uni_tam_tests.py
> fix uni againwq

- tamcolors/examples/__init__.py
- tamcolors/examples/tam_key_manager.py
- tamcolors/tam_tools/tam_key_manager.py
> add key example

- README.rst
> add youtube link

- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
- tamcolors/tests/tam_io/any_tam_tests.py
- tamcolors/tests/tam_io/win_tam_tests.py
> get_io to able_to_execute

- tamcolors/tests/tam_io/uni_tam_tests.py
> fix uni test

- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
> clean up modes

- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
> clean io tam

- tamcolors/tests/tam_io/io_tam_tests.py
> add more tests for io

- tamcolors/tam/tam_loop.py
- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
- tamcolors/tam_io/any_tam.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/win_tam.py
> Color swap

- tamcolors/tam_io/uni_tam.py
- tamcolors/tam_io/win_tam.py
- tamcolors/tests/tam_io/io_tam_tests.py
- tamcolors/tests/tam_io/uni_tam_tests.py
> color swap uni

- README.rst
- tamcolors/examples/__init__.py
- tamcolors/examples/rgb_color.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_test.py
- tamcolors/tam_io/win_tam.py
- tamcolors/tests/tam/tam_loop_test_tests.py
- tamcolors/tests/tam/tam_loop_tests.py
- tamcolors/tests/tam_io/any_tam_tests.py
- tamcolors/tests/tam_io/uni_tam_tests.py
- tamcolors/tests/tam_io/win_tam_tests.py
> dd color swap tests

- tamcolors/__init__.py
- tamcolors/tam_io/__init__.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tests/tam_io/win_drivers_tests.py
> breakup uni drivers

- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/uni_drivers.py
> add true color and uni drivers

- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io/tam_standard_tests.py
- tamcolors/tests/tam_io/win_drivers_tests.py
> add enable methods

- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/uni_drivers.py
> clean up ture drivers

- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/any_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io/any_drivers_tests.py
- tamcolors/tests/tam_io/uni_tam_tests.py
- tamcolors/tests/tam_io/win_drivers_tests.py
> add print mode

- tamcolors/tam_io/__init__.py
- tamcolors/tam_io/ansi_256_drivers.py
- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tam_io/win_drivers.py
> make 256 driver

- tamcolors/examples/icon.py
- tamcolors/examples/rgb_color.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tam_tools/tam_list_buffer.py
> break up color palette

- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam/tam_loop_tests.py
- tamcolors/tests/tam_io/any_drivers_tests.py
- tamcolors/tests/tam_io/win_drivers_tests.py
> remove set tests

- tamcolors/tam_io/ansi_true_color_drivers.py
> fix true colors

- README.rst
- setup.py
- tamcolors/__init__.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam_basic/basic.py
- tamcolors/tam_io/__init__.py
- tamcolors/tam_io/ansi_256_drivers.py
- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/any_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_keys.py
- tamcolors/tam_io/tcp_tam.py
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tests/tam_io/io_tam_tests.py
> add doc strings and tests

- tamcolors/examples/__init__.py
- tamcolors/examples/clouds.py
- tamcolors/tam_io/tam_colors.py
> Add alpha cal

- tamcolors/tam_io/ansi_256_drivers.py
- tamcolors/tam_io/ansi_true_color_drivers.py
> fix ansi buffer

- CONTRIBUTING.md
> add twine to contributing

- CONTRIBUTING.md
> clean_up_contributor

- README.rst
> add donate

- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/tam_buffer.py
- tamcolors/tam_io/tam_colors.py
- tamcolors/utils/__init__.py
- tamcolors/utils/object_packer.py
> add tambuffer bytes

- tamcolors/tam_tools/tam_placing.py
- tamcolors/utils/__init__.py
- tamcolors/utils/object_packer.py
- tamcolors/utils/transport_optimizer.py
> add transport optimizer

- tamcolors/tests/utils/__init__.py
- tamcolors/tests/utils/object_packer_tests.py
- tamcolors/tests/utils/transport_optimizer_tests.py
- tamcolors/utils/object_packer.py
> add transport tests

- tamcolors/tests/utils/__init__.py
- tamcolors/tests/utils/compress.py
- tamcolors/utils/__init__.py
- tamcolors/utils/compress.py
> add compress and tests

- README.rst
- run_slow_tests.py
- tamcolors/tests/__init__.py
- tamcolors/tests/all_tests.py
- tamcolors/tests/test_utils.py
- tamcolors/tests/utils/encryption_tests.py
- tamcolors/tests/utils/tcp_tests.py
- tamcolors/tests/utils/timer_tests.py
> add slow tests

- README.rst
> add support to all v

- .gitignore
- tamcolors/tests/utils_tests/__init__.py
- tamcolors/tests/utils_tests/identifier_tests.py
- tamcolors/tests/utils_tests/object_packer_tests.py
- tamcolors/tests/utils_tests/tcp_tests.py
- tamcolors/utils/__init__.py
- tamcolors/utils/identifier.py
- tamcolors/utils/object_packer.py
- tamcolors/utils/tcp.py
> clean up tcp and update object_packer and add identifier

- README.rst
> cut 1 1 1 goals

- tamcolors/tam_c/__init__.py
> fix missing win dll

- .gitignore
- README.rst
- tamcolors/tam_c/__init__.py
> Fix missing win dll 2

- .gitignore
- tamcolors/tam_c/__init__.py
- tamcolors/tests/tam_io_tests/uni_drivers_tests.py
> Fix mac for 1 1 1

- DEPENDENCIES.md
- README.rst
> Add 1 1 1 cut data

- README.rst
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tests/tam_io_tests/uni_drivers_tests.py
> hide mac cursor

- tamcolors/tests/tam_io_tests/uni_drivers_tests.py
> fix_uni_test_1_1_1

- setup.py
- tamcolors/__init__.py
> v to 1 1 2

- tamcolors/utils/encryption.py
- tamcolors/utils/tcp.py
1. https://github.com/cmcmarrow/tamcolors/issues/142
Moved from sha3_512 to sha512 because of compatibility issues between platforms.
> Moved from sha3_512 to sha512

- .travis.yml
- README.rst
- run_slow_tests.py
- run_tests.py
- tamcolors/docs/source/index.rst
- tamcolors/tests/all_tests.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
https://github.com/cmcmarrow/tamcolors/issues/136
add ci tests
> add ci linux test

- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tests/tam_io_tests/win_drivers_tests.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
https://github.com/cmcmarrow/tamcolors/issues/144
> add preferred mode to tam loop

- README.rst
- setup.py
- tamcolors/__init__.py
MODE_16_PAL_256 will break backwards combability
> got to v1.2.0

- tamcolors/examples/rgb_color.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/ansi_256_drivers.py
- tamcolors/tam_io/ansi_true_color_drivers.py
- tamcolors/tam_io/any_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_colors.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io_tests/tam_colors_tests.py
- tamcolors/tests/tam_io_tests/win_drivers_tests.py
https://github.com/cmcmarrow/tamcolors/issues/137
> mode_16_pal_256_win

- tamcolors/tam_c/_uni_tam_c/_uni_tam.cpp
- tamcolors/tam_c/_uni_tam_c/uni_tam.cpp
- tamcolors/tam_c/_uni_tam_c/uni_tam.h
- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
- tamcolors/tam_io/uni_drivers.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io_tests/uni_drivers_tests.py
- tamcolors/tests/tam_io_tests/win_drivers_tests.py
https://github.com/cmcmarrow/tamcolors/issues/138
> clean up cpp

- README.rst
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
fix win clear and update readme
> fix win clear and update readme

- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io_tests/win_drivers_tests.py
> lower win clear artifact rate

- tamcolors/examples/__init__.py
- tamcolors/examples/sandy_check.py
add sandy check example
https://github.com/cmcmarrow/tamcolors/issues/165
> add sandy check

- tamcolors/tam_io/win_drivers.py
fix win lock
https://github.com/cmcmarrow/tamcolors/issues/170
> fix win lock

- .gitignore
> add vs to gitignore

- setup.py
- tamcolors/tests/__init__.py
- tamcolors/tests/test_multi_task_helper.py
- tamcolors/tests/tests_tests/__init__.py
- tamcolors/tests/tests_tests/test_multi_task_helper_tests.py
- tamcolors/tests/utils_tests/__init__.py
- tamcolors/utils/tcp.py
> add multi task helper

- tamcolors/tests/utils_tests/tcp_tests.py
- tamcolors/utils/tcp.py
> add tcp tests

- tamcolors/tests/utils_tests/tcp_tests.py
- tamcolors/utils/tcp.py
this is the last major step before I can write a dummyIO.
> add obj wrap

- tamcolors/utils/tcp.py
fix send back. A `TCPObjectConnector` could have gotten the wrong return
> fix send back

- tamcolors/examples/__init__.py
- tamcolors/examples/connection_loopback.py
- tamcolors/examples/host_loopback.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tcp_io.py
- tamcolors/utils/tcp.py
> add tcp loop back

- tamcolors/examples/host_loopback.py
- tamcolors/utils/tcp.py
> make dummy io run fast

- README.rst
- tamcolors/examples/host_loopback.py
- tamcolors/examples/tabletennis.py
- tamcolors/tam/tam_loop.py
> add profiler

- README.rst
> add 1.3.0 goals

- tamcolors/examples/connection_loopback.py
- tamcolors/tests/utils_tests/tcp_tests.py
- tamcolors/tests/utils_tests/timer_tests.py
- tamcolors/utils/tcp.py
> fix tcp tests for unix

- tamcolors/utils/tcp.py
> fix tcp for win again

- README.rst
> move_back_data

- setup.py
- tamcolors/__init__.py
- tamcolors/docs/source/conf.py
> go to v1.3.0

- README.rst
> update read me 1.3.0

- tamcolors/tam/tam_loop.py
> fix clear exit

- setup.py
- tamcolors/examples/tam_key_manager.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
- tamcolors/tam_io/any_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/tam_keys.py
- tamcolors/tam_io/win_drivers.py
- tamcolors/tests/tam_io_tests/any_drivers_tests.py
- tamcolors/tests/tam_io_tests/win_drivers_tests.py
> add win get keyboard

- tamcolors/tam_c/_uni_tam_c/uni_tam.cpp
> remove double line in linux C

- README.rst
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
> fix win keyboard

- tamcolors/tam/tam_loop.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
wait key will stop multi player from making a'lot of TCP calls
> add wait key

- README.rst
> update 1.3.0 goals

- tamcolors/utils/encryption.py
> fix doc error

- tamcolors/examples/icon.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam/tam_loop_receiver.py
- tamcolors/tam/tam_loop_tcp_receiver.py
- tamcolors/tam_io/null_drivers.py
- tamcolors/tam_io/tam_colors.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/tam_surface.py
- tamcolors/tests/tam_io_tests/any_drivers_tests.py
- tamcolors/tests/tam_io_tests/tam_surface_tests.py
- tamcolors/tests/tam_io_tests/uni_drivers_tests.py
add null use handler and update icon
> add null use handler and update icon

- DEPENDENCIES.md
- setup.py
- tamcolors/tam_c/_uni_tam_c/_uni_tam.cpp
- tamcolors/tam_c/_uni_tam_c/uni_tam.cpp
- tamcolors/tam_c/_uni_tam_c/uni_tam.h
- tamcolors/tam_io/uni_drivers.py
> add lin asy input

- tamcolors/tam/tam_loop.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
> remove step

- README.rst
- tamcolors/examples/__init__.py
- tamcolors/examples/alpha.py
- tamcolors/examples/clouds.py
- tamcolors/examples/colors.py
- tamcolors/examples/connection_loopback.py
- tamcolors/examples/connection_multi_player.py
- tamcolors/examples/host_multi_player.py
- tamcolors/examples/icon.py
- tamcolors/examples/rgb_color.py
- tamcolors/examples/tabletennis.py
- tamcolors/examples/tam_key_manager.py
- tamcolors/examples/tam_list_surface.py
- tamcolors/examples/tam_loop.py
- tamcolors/examples/tam_print.py
- tamcolors/examples/tam_text_box.py
- tamcolors/tam/__init__.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam/tam_loop_io_tcp_handler.py
- tamcolors/tam/tam_loop_receiver.py
- tamcolors/tam/tam_loop_tcp_receiver.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/tcp_io.py
- tamcolors/tests/tam_tests/__init__.py
- tamcolors/tests/tam_tests/tam_loop_tcp_receiver_tests.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
- tamcolors/utils/tcp.py
> add threading to tam handler

- README.rst
- tamcolors/tam/tam_loop.py
- tamcolors/tests/tam_tests/tam_loop_tests.py
frame.frame_done is called when you pop a frame
frame.done  is called when tamloop is done when and only if its on the top of the stack
> add frame_done

- setup.py
- tamcolors/tam_c/_uni_tam_c/uni_tam.cpp
mac key state false.
`Coco` is C# and needs some works to get working in C++
Also I do not undertand `Coco`.
For now key state will just return False for Apple.
> mac key state false

- .github/FUNDING.yml
> add patreon

- README.rst
- tamcolors/docs/source/index.rst
> update docs and readme

- tamcolors/tam_c/_win_tam_c/win_tam.cpp
> fix win sub id

- tamcolors/tests/tam_io_tests/win_drivers_tests.py
> fix win test fail

- README.rst
> add road map

- tamcolors/tam_c/_uni_tam_c/uni_tam.cpp
- tamcolors/tam_io/lin_drivers.py
- tamcolors/tam_io/mac_drivers.py
> clean up Linux key state

- README.rst
> update doc for cut 1.3.0

- README.rst
- tamcolors/examples/tabletennis.py
> fix table tennis

- tamcolors/tam_io/lin_drivers.py
- tamcolors/tam_io/mac_drivers.py
> fix_mac_keys

- setup.py
> update setup version

- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam/tam_loop_io_tcp_handler.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tests/tam_io_tests/any_drivers_tests.py
> add snap shot

- tamcolors/examples/tabletennis.py
- tamcolors/examples/tam_keys.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tcp_io.py
- tamcolors/tests/tam_io_tests/any_drivers_tests.py
> add event bus

- build_scripts/build_linux_env.sh
- build_scripts/build_mac_env.sh
- build_scripts/build_win_env.bat
- tamcolors/tam_io/io_tam.py
- tamcolors/tests/tam_io_tests/any_drivers_tests.py
> add build scripts

- CONTRIBUTING.md
- build_scripts/build_linux_env.sh
- build_scripts/build_mac_env.sh
- build_scripts/build_win_env.bat
> add read com

- tamcolors/examples/rgb_color.py
- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tcp_io.py
- tamcolors/utils/tcp.py
> make tamloop use bus

- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
> add core sound to win

- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
> clean up sound tool

- tamcolors/tam/tam_loop.py
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_io/any_drivers.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/null_drivers.py
- tamcolors/tam_io/tam_drivers.py
- tamcolors/tam_io/tam_identifier.py
- tamcolors/tam_io/win_drivers.py
> add sound driver

- tamcolors/tests/utils_tests/__init__.py
- tamcolors/tests/utils_tests/id_manager_tests.py
- tamcolors/utils/id_manager.py
add id manager tests and fix bugs
> add id manager tests and fix bugs

- tamcolors/tests/utils_tests/__init__.py
- tamcolors/tests/utils_tests/path_tests.py
> add path tests

- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/tcp_io.py
> add running to io snap shot

- README.rst
> remove pass versions

- tamcolors/tam/tam_loop.py
- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam_io/io_tam.py
- tamcolors/tam_io/win_drivers.py
> add loop log

- tamcolors/tam/tam_loop.py
- tamcolors/tests/utils_tests/log_tests.py
- tamcolors/utils/log.py
- tamcolors/utils/tcp.py
> Add tam log stream

- tamcolors/tam/tam_loop.py
> remove print from loop

- tamcolors/examples/tabletennis.py
- tamcolors/tam/tam_loop.py
- tamcolors/utils/timer.py
> add fps to loop

- tamcolors/tam/tam_loop_io_handler.py
- tamcolors/tam_c/_win_tam_c/_win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.cpp
- tamcolors/tam_c/_win_tam_c/win_tam.h
- tamcolors/tam_io/win_drivers.py
> move to win to ansi
